import 'package:flutter/material.dart';

void main() => runApp(const CatalogoApp());

class CatalogoApp extends StatelessWidget {
  const CatalogoApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(debugShowCheckedModeBanner: false, title: 'Catálogo UI', theme: ThemeData(colorScheme: ColorScheme.fromSeed(seedColor: Colors.indigo)), darkTheme: ThemeData(colorScheme: ColorScheme.fromSeed(seedColor: Colors.indigo, brightness: Brightness.dark)), themeMode: ThemeMode.system, home: const CatalogoPage());
}

class CatalogoPage extends StatefulWidget { const CatalogoPage({super.key}); @override State<CatalogoPage> createState() => _CatalogoPageState(); }
class _CatalogoPageState extends State<CatalogoPage> {
  int indice = 0; String compartido = ''; bool cargando = false; bool switchValue = true; bool marcado = false; String opcion = 'A'; String chip = 'Diseño'; double valor = .4; final nombre = TextEditingController(); final elementos = List<String>.generate(15, (i) => 'Elemento de catálogo ${i + 1}');
  final secciones = const ['Entrada', 'Acciones', 'Selección', 'Listas', 'Información', 'Estructura'];
  void mensaje(String texto) => ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(texto), action: SnackBarAction(label: 'Cerrar', onPressed: () {})));
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: Text('Catálogo UI · ${secciones[indice]}'), actions: [IconButton(onPressed: () => mensaje('Catálogo de componentes interactivos'), icon: const Icon(Icons.info_outline))]), body: RefreshIndicator(onRefresh: () async => mensaje('Lista actualizada'), child: ListView(padding: const EdgeInsets.all(16), children: [Text('Elementos básicos de interfaz', style: Theme.of(context).textTheme.headlineSmall), const Text('Cada muestra es interactiva y está documentada en español.'), const SizedBox(height: 12), _seccion()])), bottomNavigationBar: NavigationBar(selectedIndex: indice, onDestinationSelected: (i) => setState(() => indice = i), destinations: secciones.map((s) => NavigationDestination(icon: const Icon(Icons.widgets_outlined), label: s)).toList()), floatingActionButton: indice == 1 ? FloatingActionButton.extended(onPressed: () => mensaje('Acción flotante ejecutada'), icon: const Icon(Icons.add), label: const Text('Nueva acción')) : null);
  Widget _demo(String titulo, String descripcion, Widget child) => Card(child: Padding(padding: const EdgeInsets.all(16), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(titulo, style: Theme.of(context).textTheme.titleMedium), Text(descripcion), const SizedBox(height: 12), child])));
  Widget _seccion() => switch (indice) { 0 => _entrada(), 1 => _acciones(), 2 => _seleccion(), 3 => _listas(), 4 => _informacion(), _ => _estructura() };
  Widget _entrada() => Column(children: [_demo('Campo de texto', 'Captura información breve y valida datos antes de compartirlos.', TextField(controller: nombre, decoration: InputDecoration(labelText: 'Nombre para la lista', errorText: nombre.text.isEmpty ? 'El nombre es obligatorio' : null), onChanged: (_) => setState(() {}))), _demo('Contraseña y teclados', 'Usa ocultamiento y tipos de teclado especializados.', Column(children: [TextField(obscureText: true, decoration: const InputDecoration(labelText: 'Contraseña')), TextField(keyboardType: TextInputType.emailAddress, decoration: const InputDecoration(labelText: 'Correo electrónico')), const TextField(maxLines: 3, decoration: InputDecoration(labelText: 'Comentario multilínea')), const TextField(decoration: InputDecoration(labelText: 'Buscar', prefixIcon: Icon(Icons.search)))])), SwitchListTile(title: const Text('Sugerencias automáticas'), value: switchValue, onChanged: (v) => setState(() => switchValue = v)), FilledButton.icon(onPressed: nombre.text.isEmpty ? null : () { compartido = nombre.text; mensaje('Dato agregado a Listas'); setState(() {}); }, icon: const Icon(Icons.add), label: const Text('Agregar a Listas'))]);
  Widget _acciones() => Column(children: [_demo('Botones y acciones', 'Cada control responde con un mensaje visible.', Wrap(spacing: 8, runSpacing: 8, children: [FilledButton(onPressed: () => mensaje('Botón relleno'), child: const Text('Relleno')), OutlinedButton(onPressed: () => mensaje('Botón con contorno'), child: const Text('Contorno')), TextButton(onPressed: () => mensaje('Botón de texto'), child: const Text('Solo texto')), IconButton(onPressed: () => mensaje('Ícono pulsado'), icon: const Icon(Icons.delete)), FilledButton.icon(onPressed: () => mensaje('Acción con ícono'), icon: const Icon(Icons.add), label: const Text('Agregar')), FilledButton(onPressed: null, child: const Text('Deshabilitado'))])), _demo('Estado de carga', 'El indicador comunica que una tarea está en proceso.', Column(children: [LinearProgressIndicator(value: cargando ? null : .65), const SizedBox(height: 10), OutlinedButton(onPressed: () { setState(() => cargando = !cargando); }, child: Text(cargando ? 'Detener carga' : 'Iniciar carga'))]))]);
  Widget _seleccion() => Column(children: [_demo('Elementos de selección', 'Checkbox, radio, interruptor y chips permiten combinar decisiones.', Column(children: [CheckboxListTile(value: marcado, tristate: true, onChanged: (v) => setState(() => marcado = v ?? false), title: const Text('Casilla seleccionable')), RadioListTile(value: 'A', groupValue: opcion, onChanged: (v) => setState(() => opcion = v!), title: const Text('Opción A')), RadioListTile(value: 'B', groupValue: opcion, onChanged: (v) => setState(() => opcion = v!), title: const Text('Opción B')), SwitchListTile(value: switchValue, onChanged: (v) => setState(() => switchValue = v), title: const Text('Interruptor')), Slider(value: valor, onChanged: (v) => setState(() => valor = v)), DropdownButton<String>(value: opcion, items: ['A', 'B', 'C'].map((v) => DropdownMenuItem(value: v, child: Text('Opción $v'))).toList(), onChanged: (v) => setState(() => opcion = v!)), Wrap(spacing: 6, children: ['Diseño', 'Accesibilidad', 'Android'].map((v) => FilterChip(label: Text(v), selected: chip == v, onSelected: (_) => setState(() => chip = v))).toList()), OutlinedButton(onPressed: () async { await showDatePicker(context: context, firstDate: DateTime(2020), lastDate: DateTime(2030), initialDate: DateTime.now()); }, child: const Text('Selector de fecha')), OutlinedButton(onPressed: () async { await showTimePicker(context: context, initialTime: TimeOfDay.now()); }, child: const Text('Selector de hora'))]))]);
  Widget _listas() {
    final filas = <Widget>[];
    if (compartido.isNotEmpty) filas.add(Text('Dato recibido desde Entrada: $compartido'));
    for (final elemento in elementos) {
      filas.add(ListTile(
        title: Text(elemento),
        trailing: IconButton(icon: const Icon(Icons.delete_outline), tooltip: 'Eliminar', onPressed: () => setState(() => elementos.remove(elemento))),
        onTap: () => showDialog(context: context, builder: (_) => AlertDialog(title: const Text('Detalle'), content: Text('Información de $elemento'), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cerrar'))])),
      ));
    }
    if (elementos.isEmpty) filas.add(const Text('Estado vacío: no hay elementos'));
    filas.add(OutlinedButton(onPressed: () => mensaje('Lista actualizada'), child: const Text('Actualizar lista')));
    filas.add(DefaultTabController(length: 3, child: Column(children: [const TabBar(tabs: [Tab(text: 'Recientes'), Tab(text: 'Favoritos'), Tab(text: 'Archivados')]), SizedBox(height: 80, child: TabBarView(children: [const Center(child: Text('Encabezado recientes')), const Center(child: Text('Encabezado favoritos')), const Center(child: Text('Encabezado archivados'))]))])));
    filas.add(GridView.count(crossAxisCount: 2, shrinkWrap: true, physics: const NeverScrollableScrollPhysics(), children: const [Card(child: Center(child: Text('A1'))), Card(child: Center(child: Text('A2'))), Card(child: Center(child: Text('B1'))), Card(child: Center(child: Text('B2')))]));
    return Column(children: [_demo('Listas y colecciones', 'Toca un elemento para consultar detalle; el botón permite eliminarlo.', Column(children: filas))]);
  }
  Widget _informacion() => Column(children: [_demo('Información y retroalimentación', 'Los mensajes explican estados, avances y resultados.', Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Título grande', style: Theme.of(context).textTheme.headlineSmall), const Text('Texto destacado', style: TextStyle(fontWeight: FontWeight.bold)), const Icon(Icons.image_outlined, size: 56, semanticLabel: 'Imagen local'), const Text('Imagen local: icono incluido'), Image.network('https://picsum.photos/200', height: 120, width: 200, fit: BoxFit.cover, errorBuilder: (_, __, ___) => const Text('Imagen remota no disponible')), const Text('Imagen remota: https://picsum.photos/200'), const LinearProgressIndicator(value: .65), const SizedBox(height: 12), const CircularProgressIndicator(), FilledButton(onPressed: () => mensaje('Snackbar con acción'), child: const Text('Mostrar snackbar')), OutlinedButton(onPressed: () => showModalBottomSheet(context: context, builder: (_) => const Padding(padding: EdgeInsets.all(24), child: Text('Hoja inferior interactiva'))), child: const Text('Abrir hoja inferior')), Row(children: [const Text('Tarjeta y separador'), const SizedBox(width: 12), Badge(label: const Text('3'))]), const Divider()]))]);
  Widget _estructura() => Column(children: [_demo('Contenedores y estructura', 'La pantalla combina fila, columna, superposición, desplazamiento y navegación.', Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceAround, children: const [Text('Fila 25%'), Text('Fila 50%'), Text('Fila 25%')]), const Text('Columna: elemento 1\nColumna: elemento 2'), const Stack(children: [Text('Superposición: contenido principal'), Positioned(right: 0, child: Badge(label: Text('3')))]), const Text('Barra superior con título y acciones\nBarra inferior con seis destinos\nContenedor con desplazamiento vertical')]))]);
}
