package com.example.helloandroid

import android.app.AlertDialog
import android.app.DatePickerDialog
import android.app.TimePickerDialog
import android.graphics.Color
import android.os.Bundle
import android.text.InputType
import android.view.View
import android.widget.*
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity

class MainActivity : AppCompatActivity() {
    private lateinit var content: LinearLayout
    private var compartido = ""
    private val elementos = (1..15).map { "Elemento de catálogo $it" }.toMutableList()
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState); enableEdgeToEdge(); setContentView(R.layout.activity_main); content = findViewById(R.id.content)
        val navigation = findViewById<LinearLayout>(R.id.navigation)
        listOf("Entrada", "Acciones", "Selección", "Listas", "Información", "Estructura").forEachIndexed { index, label -> Button(this).apply { text = label; setOnClickListener { showSection(index) }; navigation.addView(this) } }; showSection(0)
    }
    private fun label(value: String, size: Float = 16f) = TextView(this).apply { text = value; textSize = size; setPadding(8, 12, 8, 6) }
    private fun header(name: String, description: String) { content.addView(label(name, 21f)); content.addView(label(description, 14f)) }
    private fun showSection(index: Int) { content.removeAllViews(); when (index) { 0 -> entrada(); 1 -> acciones(); 2 -> seleccion(); 3 -> listas(); 4 -> informacion(); else -> estructura() } }
    private fun entrada() { header("Entrada de texto", "Captura datos con etiquetas, validación y distintos tipos de teclado."); val nombre = EditText(this).apply { hint = "Nombre para la lista"; inputType = InputType.TYPE_CLASS_TEXT }; content.addView(nombre); val error = label("El nombre es obligatorio", 13f); error.setTextColor(Color.RED); error.visibility = View.GONE; content.addView(error); content.addView(EditText(this).apply { hint = "Contraseña"; inputType = InputType.TYPE_CLASS_TEXT or InputType.TYPE_TEXT_VARIATION_PASSWORD }); content.addView(EditText(this).apply { hint = "Correo electrónico"; inputType = InputType.TYPE_CLASS_TEXT or InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS }); content.addView(EditText(this).apply { hint = "Teléfono"; inputType = InputType.TYPE_CLASS_PHONE }); content.addView(EditText(this).apply { hint = "Comentario multilínea"; minLines = 3 }); content.addView(AutoCompleteTextView(this).apply { hint = "Buscar o elegir sugerencia"; setAdapter(ArrayAdapter(context, android.R.layout.simple_dropdown_item_1line, listOf("Android", "Compose", "Flutter"))) }); content.addView(Switch(this).apply { text = "Sugerencias automáticas" }); content.addView(Button(this).apply { text = "Agregar a Listas"; setOnClickListener { if (nombre.text.isNullOrBlank()) error.visibility = View.VISIBLE else { error.visibility = View.GONE; compartido = nombre.text.toString(); Toast.makeText(context, "Dato compartido con Listas", Toast.LENGTH_SHORT).show() } } }) }
    private fun acciones() { header("Botones y acciones", "Cada botón produce una respuesta visible y muestra distintos niveles de énfasis."); listOf("Botón relleno", "Botón con contorno", "Botón solo texto", "Ícono + texto", "FAB normal", "FAB extendido").forEach { value -> content.addView(Button(this).apply { text = value; setOnClickListener { Toast.makeText(context, "$value pulsado", Toast.LENGTH_SHORT).show() } }) }; content.addView(Button(this).apply { text = "Deshabilitado"; isEnabled = false }); content.addView(ProgressBar(this).apply { isIndeterminate = true }) }
    private fun seleccion() { header("Elementos de selección", "Permiten elegir opciones, estados y valores dentro de un formulario."); var estado = 0; content.addView(CheckBox(this).apply { text = "Casilla: indeterminada"; setOnClickListener { estado = (estado + 1) % 3; isChecked = estado == 2; text = when (estado) { 0 -> "Casilla: sin marcar"; 1 -> "Casilla: indeterminada"; else -> "Casilla: marcada" } } }); content.addView(RadioGroup(this).apply { orientation = RadioGroup.VERTICAL; addView(RadioButton(context).apply { id = View.generateViewId(); text = "Opción A" }); addView(RadioButton(context).apply { id = View.generateViewId(); text = "Opción B" }) }); content.addView(Switch(this).apply { text = "Interruptor" }); content.addView(SeekBar(this).apply { max = 100; progress = 40 }); content.addView(Spinner(this).apply { adapter = ArrayAdapter(context, android.R.layout.simple_spinner_dropdown_item, listOf("Selección A", "Selección B", "Selección C")) }); content.addView(Button(this).apply { text = "Selector de fecha"; setOnClickListener { val now = java.util.Calendar.getInstance(); DatePickerDialog(context, { _, y, m, d -> Toast.makeText(context, "$d/${m + 1}/$y", Toast.LENGTH_SHORT).show() }, now.get(java.util.Calendar.YEAR), now.get(java.util.Calendar.MONTH), now.get(java.util.Calendar.DAY_OF_MONTH)).show() } }); content.addView(Button(this).apply { text = "Selector de hora"; setOnClickListener { val now = java.util.Calendar.getInstance(); TimePickerDialog(context, { _, h, m -> Toast.makeText(context, "%02d:%02d".format(h, m), Toast.LENGTH_SHORT).show() }, now.get(java.util.Calendar.HOUR_OF_DAY), now.get(java.util.Calendar.MINUTE), true).show() } }); content.addView(label("Chips interactivos: selecciona una o más etiquetas")); val chips = LinearLayout(this).apply { orientation = LinearLayout.HORIZONTAL }; listOf("Diseño", "Accesibilidad", "Android").forEach { value -> chips.addView(CheckBox(this).apply { text = value }) }; content.addView(chips) }
    private fun listas() { header("Listas y colecciones", "Pulsa una fila para consultar su información y usa Eliminar para quitarla."); if (compartido.isNotBlank()) content.addView(label("Dato recibido desde Entrada: $compartido")); elementos.toList().forEach { value -> content.addView(Button(this).apply { text = "$value   Eliminar"; setOnClickListener { elementos.remove(value); listas() } }) }; if (elementos.isEmpty()) content.addView(label("Estado vacío: no hay elementos")); content.addView(Button(this).apply { text = "Actualizar lista"; setOnClickListener { Toast.makeText(context, "Lista actualizada", Toast.LENGTH_SHORT).show() } }); content.addView(label("Cuadrícula: A1 · A2 · B1 · B2\nEncabezados: Recientes / Favoritos\nPestañas: Recientes · Favoritos · Archivados")) }
    private fun informacion() { header("Información y retroalimentación", "Comunica estados, avances y resultados de las acciones del usuario."); content.addView(label("Título grande y texto destacado", 24f)); content.addView(label("Imagen local: recurso de la aplicación\nImagen URL: https://picsum.photos/200")); content.addView(ProgressBar(this, null, android.R.attr.progressBarStyleHorizontal).apply { max = 100; progress = 65 }); content.addView(ProgressBar(this)); content.addView(Button(this).apply { text = "Snackbar / Toast"; setOnClickListener { Toast.makeText(context, "Mensaje breve con acción", Toast.LENGTH_LONG).show() } }); content.addView(Button(this).apply { text = "Diálogo de confirmación"; setOnClickListener { AlertDialog.Builder(context).setTitle("¿Confirmar?").setMessage("Esta acción requiere confirmación.").setPositiveButton("Confirmar", null).setNegativeButton("Cancelar", null).show() } }); content.addView(label("Tarjeta de información | Separador | Badge: 3")) }
    private fun estructura() { header("Contenedores y estructura", "Ejemplos de fila, columna, superposición, desplazamiento y distribución proporcional."); content.addView(label("Fila: 25% · 50% · 25%")); content.addView(label("Columna: elemento 1\nColumna: elemento 2\nSuperposición: contenido + badge\nBarra superior con título y acciones\nBarra de navegación inferior\nContenedor con desplazamiento vertical")) }
}
